site_name: ScanPoint
site_url: "https://fga-pi2.gitlab.io/"
site_dir: public
theme:
  name: material
  favicon: assets/scanpoint-logo.png
  features:
    - content.code.annotate
    - content.tabs.link
    - header.autohide
    - navigation.instant
    - navigation.sections
    - navigation.tabs
    - navigation.top
    - navigation.tracking
extra_css:
  - stylesheets/styles.css
nav:
  - Sobre: index.md
  - Geral: 
      - Anexo: geral/anexo.md
      - Apendice: geral/apendice1.md
      - Arquitetura: geral/arquitetura.md
      - Bib: geral/bib.md
      - Integracao: geral/integracao.md
      - Levantamento de riscos: geral/FMEA.md
      - Projetos: geral/projetos.md
      - Prova de conceito: geral/prova-de-conceito.md
      - Requisitos de arquitetura: geral/requisitos.md
      - Visao geral: geral/visaogeral.md
  - Software: 
      - Diagrama de pacotes: software/diagrama-de-pacotes.md
      - Casos de uso: software/casos-de-uso.md
      - Diagrama de protocolos de comunicacao de software: software/protocolos-de-comunicacao-software.md
      - Arquitetura de software: software/arquitetura.md
  - Eletrônica/Energia: 
      - Exemplo: eletronica-energia/exemplo.md
  - Estruturas:
      - Exemplo: estruturas/exemplo.md
