site_name: ScanPoint
site_url: "https://fga-pi2.gitlab.io/"
site_dir: public
theme:
  name: material
  favicon: assets/scanpoint-logo.png
  features:
    - content.code.annotate
    - content.tabs.link
    - header.autohide
    - navigation.instant
    - navigation.sections
    - navigation.tabs
    - navigation.top
    - navigation.tracking
extra_css:
  - stylesheets/styles.css
nav:
  - Sobre: index.md
  - Geral: 
      - Arquitetura: geral/arquitetura.md
      - Cronograma: geral/cronograma.md
      - EAP: geral/eap_geral.md
      - Estimativa de Custos: geral/estimativa-custos.md
      - Levantamento de riscos: geral/FMEA.md
      - Integracao: geral/integracao.md
      - Normas: geral/normas.md
      - Projetos: geral/projetos.md
      - Prova de conceito: geral/prova-de-conceito.md
      - Requisitos Gerais: geral/requisitos.md
      - Termo de Abertura: geral/termo_de_abertura_de_projeto.md
      - Visao geral: geral/visaogeral.md
  - Software: 
      - Arquitetura de software: software/arquitetura.md
      - Backlog do produto: software/backlog_produto.md
      - Casos de uso: software/casos-de-uso.md
      - Diagrama BPMN: software/diagrama-bpmn.md
      - Diagrama de pacotes: software/diagrama-de-pacotes.md
      - EAP: software/eap_software.md
      - Funcionalidades: software/funcionalidades.md
      - Documento de identidade: software/identidade.md
      - Prototipo de alta fidelidade: software/prototipo.md
      - Requisitos de software: software/requisitos.md
      - Projeto de subsistema de software: software/subsistema-software.md
  - Eletrônica/Energia: 
      - Arquitetura de eletronica: eletronica-energia/arquitetura_subsist_eletronica.md
      - Arquitetura de energia: eletronica-energia/arquitetura_energia.md
      - EAP: eletronica-energia/eap.md
      - Subsistema de eletronica: eletronica-energia/arquitetura_subsist_eletronica.md
      - Subsistema de energia: eletronica-energia/Projeto_Subsistema_Energia.md
      - Requisitos: eletronica-energia/requisitos-eletronica-energia.md
  - Estruturas:
      - Arquitetura: estruturas/arquitetura_subs_estruturas.md
      - Desenhos mecanicos: estruturas/DTs.md
      - EAP: estruturas/EAP_estruturas.md
      - Subsistema de Estruturas: estruturas/Projeto_subsistema_estruturas.md
      - Requisitos: estruturas/Requisitos_estruturas.md

