site_name: Communication Box
site_url: "https://fga-pi2.gitlab.io/"
site_dir: public
theme:
  name: material
  favicon: assets/communication-box-logo.png
  features:
    - content.code.annotate
    - content.tabs.link
    - header.autohide
    - navigation.instant
    - navigation.sections
    - navigation.tabs
    - navigation.top
    - navigation.tracking
extra_css:
  - stylesheets/styles.css
nav:
  - Sobre: index.md
  - Geral: 
      - anexo: geral/anexo.md
      - apendice: geral/apendice1.md
      - arquitetura: geral/arquitetura.md
      - bib: geral/bib.md
      - integracao: geral/integracao.md
      - levantamento de riscos: geral/FMEA.md
      - projetos: geral/projetos.md
      - prova de conceito: geral/prova-de-conceito.md
      - requisitos de arquitetura: geral/requisitos-arquitetura.md
      - visao geral: geral/visaogeral.md
  - Software: 
      - Exemplo: software/exemplo.md
  - Eletrônica/Energia: 
      - Exemplo: eletronica-energia/exemplo.md
  - Estruturas:
      - Exemplo: estruturas/exemplo.md
